import asyncio
import json
import os

from dotenv import load_dotenv
from groq import Groq

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client


load_dotenv()

groq_client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

server_params = StdioServerParameters(
    command="python",
    args=["server.py"],
)

MODEL = "openai/gpt-oss-120b"


SYSTEM_PROMPT = """
You are DevIntel, an AI software engineering assistant.

Your job is to help developers understand and analyze their
local software repositories.

You have access to tools through an MCP server.

Your capabilities include:

- Analyzing repository statistics
- Inspecting project structure
- Searching source code
- Reading repository files
- Checking Git status
- Viewing Git history
- Viewing Git diffs
- Discovering test files
- Detecting project technologies

Rules:

1. Use MCP tools whenever repository information is required.
2. Never invent information about the repository.
3. Choose the most appropriate tool for the user's request.
4. Use the repository path provided by the user.
5. After receiving tool results, explain them clearly.
6. If more information is needed, use another available tool.
"""


# Convert MCP tools to Groq tools

def convert_mcp_tools(mcp_tools):

    groq_tools = []

    for tool in mcp_tools:

        groq_tools.append({
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description or "",
                "parameters": tool.input_schema,
            }
        })

    return groq_tools


# Run the agent for one user message

async def run_agent(session, groq_tools, messages):

    while True:

        response = groq_client.chat.completions.create(
            model=MODEL,
            messages=messages,
            tools=groq_tools,
            tool_choice="auto",
        )

        message = response.choices[0].message

        # No tool call so final answer

        if not message.tool_calls:

            messages.append({
                "role": "assistant",
                "content": message.content
            })

            print("\nDevIntel:")
            print(message.content)

            return

        # Add assistant tool calls to conversation

        messages.append({
            "role": "assistant",
            "content": message.content,
            "tool_calls": [
                {
                    "id": tool_call.id,
                    "type": "function",
                    "function": {
                        "name": tool_call.function.name,
                        "arguments": tool_call.function.arguments,
                    }
                }
                for tool_call in message.tool_calls
            ]
        })

        # Execute all requested MCP tools

        for tool_call in message.tool_calls:

            tool_name = tool_call.function.name

            try:
                arguments = json.loads(
                    tool_call.function.arguments
                )

            except json.JSONDecodeError:

                result_text = (
                    "Invalid JSON arguments generated by the model."
                )

                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": result_text
                })

                continue

            print(f"\n🔧 Calling tool: {tool_name}")
            print(f"Arguments: {arguments}")

            try:

                result = await session.call_tool(
                    tool_name,
                    arguments
                )

                result_text = ""

                for content in result.content:

                    if hasattr(content, "text"):
                        result_text += content.text
                    else:
                        result_text += str(content)

                print("✓ Tool completed")
                print(f"Result length: {len(result_text)} characters")

            except Exception as e:

                print(f"❌ Tool failed: {e}")

                result_text = f"Tool execution failed: {str(e)}"

            # Send result back to Groq

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": result_text
            })

        # Loop again
        # Groq can now decide whether it needs another tool.




async def main():

    print("\n========================================")
    print("        DevIntel AI Assistant")
    print("========================================\n")

    async with stdio_client(server_params) as (read, write):

        async with ClientSession(read, write) as session:

            # Initialize MCP

            await session.initialize()

            # Discover tools

            tools_result = await session.list_tools()

            mcp_tools = tools_result.tools

            print("Connected to DevIntel MCP Server.")
            print(f"Loaded {len(mcp_tools)} tools.\n")

            groq_tools = convert_mcp_tools(mcp_tools)

            # Conversation history

            messages = [
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                }
            ]

            # Interactive loop

            while True:

                try:
                    user_message = input("\nYou: ")

                except (KeyboardInterrupt, EOFError):

                    print("\n\nGoodbye!")
                    break

                # Ignore empty messages

                if not user_message.strip():
                    continue

                if user_message.lower().strip() in {
                    "exit",
                    "quit",
                    "bye"
                }:

                    print("\nGoodbye! 👋")
                    break

                # Add user message to history

                messages.append({
                    "role": "user",
                    "content": user_message
                })

                # Run agent

                try:

                    await run_agent(
                        session,
                        groq_tools,
                        messages
                    )

                except Exception as e:

                    print(
                        f"\n❌ Agent error: {str(e)}"
                    )




if __name__ == "__main__":
    asyncio.run(main())